include(LOGGER) #cmake logger
list(APPEND APP_SRC_LIST
    ${PROJECT_SOURCE_DIR}/Src/main.c
    ${PROJECT_SOURCE_DIR}/Inc/main.h
    )
set(APP_SRC_FILES ${APP_SRC_LIST} CACHE INTERNAL "") 

list(APPEND APP_INC_LIST
    ${PROJECT_SOURCE_DIR}/Inc
    )
set(APP_INC_PATH ${APP_INC_LIST} CACHE INTERNAL "") 

