if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[m")
  set(ColourBold  "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")
endif()

# Example
#message("This is normal")
#message("${Red}This is Red${ColourReset}")
#message("${Green}This is Green${ColourReset}")
#message("${Yellow}This is Yellow${ColourReset}")
#message("${Blue}This is Blue${ColourReset}")
#message("${Magenta}This is Magenta${ColourReset}")
#message("${Cyan}This is Cyan${ColourReset}")
#message("${White}This is White${ColourReset}")
#message("${BoldRed}This is BoldRed${ColourReset}")
#message("${BoldGreen}This is BoldGreen${ColourReset}")
#message("${BoldYellow}This is BoldYellow${ColourReset}")
#message("${BoldBlue}This is BoldBlue${ColourReset}")
#message("${BoldMagenta}This is BoldMagenta${ColourReset}")
#message("${BoldCyan}This is BoldCyan${ColourReset}")
#message("${BoldWhite}This is BoldWhite\n\n${ColourReset}")

# custom log colour
if(NOT WIN32)
    set(LOG_WARN ${Yellow})
    set(LOG_INFO ${Green})
    set(LOG_ERR ${Red})
endif()
list(APPEND LOG_TYPE LOG_WARN LOG_INFO LOG_ERR)
#message("${LOG_TYPE}")


function(LOGGER LTYPE LOG_MESSAGE)
    if(LTYPE IN_LIST LOG_TYPE)
        if(${LTYPE} STREQUAL LOG_ERR)
            message(FATAL_ERROR "${${LTYPE}}-> ${LOG_MESSAGE} ${ColourReset}")
        else()
            message("${${LTYPE}}-> ${LOG_MESSAGE} ${ColourReset}")
        endif(${LTYPE} STREQUAL LOG_ERR)
    endif(LTYPE IN_LIST LOG_TYPE)
endfunction()

# Example
#LOGGER(LOG_WARN "WARNING")
#LOGGER(LOG_INFO "INFO")
#LOGGER(LOG_ERR "ERROR")
