# list of supported MCU
list(APPEND MCU_LIST 
    STM32L496xx
    )

#########################################################################
# STM_HAL_INIT
#########################################################################
function(STM_HAL_INIT STM_MCU)
    if(${STM_MCU} STREQUAL STM32L496xx)
        add_definitions(-DUSE_HAL_DRIVER -DSTM32L496xx)
        # Set linker and GCC flags fot MCU
        set(STM_LINKER_PATH "${PROJECT_SOURCE_DIR}")
        set(LINKER_SCRIPT ${STM_LINKER_PATH}/STM32L496ZGTx_FLASH.ld)
        include(stm32l4)
        
        # STM32CUBEMX autogenerated board config
        list(APPEND STM_HAL_INIT_SRC
            # board config (autognerated)
            ${PROJECT_SOURCE_DIR}/Src/stm32l4xx_hal_msp.c
            ${PROJECT_SOURCE_DIR}/Src/stm32l4xx_it.c
            ${PROJECT_SOURCE_DIR}/Src/system_stm32l4xx.c
            #startup file
            ${PROJECT_SOURCE_DIR}/startup_stm32l496xx.s
            )
        set(MCU_HAL_INIT_SRC ${STM_HAL_INIT_SRC} CACHE INTERNAL "")

        # HAL Drivers -> muss be included first
        add_subdirectory(${PROJECT_SOURCE_DIR}/Drivers)
        set(MCU_HAL_DRIVER STM32L4xx_HAL_Driver CACHE INTERNAL "")
    else()
        LOGGER(LOG_ERR "MCU ${STM_MCU} not supported")
    endif(${STM_MCU} STREQUAL STM32L496xx)
endfunction(STM_HAL_INIT STM_MCU)

#########################################################################
# MCU_HAL_INIT
#########################################################################
function(MCU_HAL_INIT MCU)
    if(NOT ${MCU} IN_LIST ${MCU_LIST})
        LOGGER(LOG_ERR "MCU ${MCU} not supported")
    endif(NOT ${MCU} IN_LIST ${MCU_LIST})

    if(${MCU} STREQUAL STM32L496xx)
        LOGGER(LOG_INFO "initializing HAL for ${MCU} ")
        STM_HAL_INIT(${MCU})
    endif(${MCU} STREQUAL STM32L496xx)
endfunction(MCU_HAL_INIT MCU)
